### ISSUE TITLE
Playback state query

### ISSUE THREAD

**Issue by Temujin2887** [AloyseTech/Zerodio#4]
Because the library is non blocking, i need a way to detect the state of the audio playback. 

`bool playing();`

**Comment by AloyseTech** [comment]
Could you please try the lib from the branch [timing_function](https://github.com/AloyseTech/Zerodio/tree/timing_function) ?  I still haven't any setup to test it. But it should work.

**Comment by Temujin2887** [comment]
There's a typo in the implementation of the isPlaying function (isP**L**aying). I corrected that and it seems to be working fine.

**Comment by AloyseTech** [comment]
Corrected the typo, thanks
